/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeAvatar: typeof import('primevue/avatar')['default']
    PrimeButton: typeof import('primevue/button')['default']
    PrimeCard: typeof import('primevue/card')['default']
    PrimeChart: typeof import('primevue/chart')['default']
    PrimeCheckbox: typeof import('primevue/checkbox')['default']
    PrimeColumn: typeof import('primevue/column')['default']
    PrimeDataTable: typeof import('primevue/datatable')['default']
    PrimeDialog: typeof import('primevue/dialog')['default']
    PrimeDivider: typeof import('primevue/divider')['default']
    PrimeDrawer: typeof import('primevue/drawer')['default']
    PrimeFloatLabel: typeof import('primevue/floatlabel')['default']
    PrimeInputNumber: typeof import('primevue/inputnumber')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimeMenu: typeof import('primevue/menu')['default']
    PrimeMessage: typeof import('primevue/message')['default']
    PrimePassword: typeof import('primevue/password')['default']
    PrimeProgressBar: typeof import('primevue/progressbar')['default']
    PrimeSelect: typeof import('primevue/select')['default']
    PrimeSidebar: typeof import('primevue/sidebar')['default']
    PrimeSplitButton: typeof import('primevue/splitbutton')['default']
    PrimeStepPanel: typeof import('primevue/steppanel')['default']
    PrimeToast: typeof import('primevue/toast')['default']
    PrimeToolbar: typeof import('primevue/toolbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
